### ISSUE TITLE
Support `useFormContext`

### ISSUE THREAD

**Issue by andykao1213** [andykao1213/eslint-plugin-react-hook-form#16]
As mentioned in the #13 , we should probably support `useFormContext`.

**Comment by getTobiasNielsen** [comment]
I thought maybe I could help.

Would it be totally out of the question to make this whole project TS, but also able to parse at a TS level?

**Comment by andykao1213** [comment]
@getTobiasNielsen please feel free to open a PR for this!

> Would it be totally out of the question to make this whole project TS, but also able to parse at a TS level?
I don't really understand your question. Do you mean if the rules from this plugin support TypeScript?

**Comment by getTobiasNielsen** [comment]
> I don't really understand your question. Do you mean if the rules from this plugin support TypeScript?

Making it so, the rules would also be able to apply to TS features, I've done some research, there are two points to this:

- One is that it might make it easier to identify when something is from RHF when the linter understands TS.
- Second that there are some people that try to use RHF in a way that is in conflict with typescript, because large parts of RHF is invariant, and it might make sense to warn there that the typescript errors they see are due to the invariant nature, and possibly suggest a cast that doesn't conflict with their use. How easy this would be is still unclear to me, but it would be possible to detect in theory down the line.

Besides that, I also meant, converting the project/plugin to TS for the fun of it, although not critical.

**Comment by andykao1213** [comment]
> One is that it might make it easier to identify when something is from RHF when the linter understands TS.

Do you mean if there's another api call `useForm` but it is not from RHF, the plugin should be able to identify this and avoid false alarm? I think it's a good idea.

> Second that there are some people that try to use RHF in a way that is in conflict with typescript, because large parts of RHF is invariant, and it might make sense to warn there that the typescript errors they see are due to the invariant nature, and possibly suggest a cast that doesn't conflict with their use. How easy this would be is still unclear to me, but it would be possible to detect in theory down the line.

Could you give an example how people will use RHF conflict with Typescript?

> Besides that, I also meant, converting the project/plugin to TS for the fun of it, although not critical.

Yeah I actually think about this before. I think the challenging part will be there's no proper type definition for the AST parser. But once this is setup, it's worth to contribute the type definition back to the eslint community.

**Comment by andykao1213** [comment]
Since the original topic is resolved, I'm closing this issue.
Please feel free to create new issue to track on other topic we discussed here.
Cheers!
